# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74355753b510800e8f359b3da78249cfcb7b4284e8f1c3ac96e554906270cd6aff121ea06886b6063eafae69d81b4dd1dfc8c085383b43b48bc209ffa26febbb

test:
  secret_key_base: e2eacf0f74f1e768ec43261f46baf90eef994b8a10c8d1a1398653c4e5c5a1f02ef4aea8969d96c27fe5b0816ef917302a2d1145b98adbd92ca7fb4809a849e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
